<?php return [
    "/" =>"./guis/index.gui.php",
    "/home"=>"./guis/home.gui.php",
    "/signin"=>"./guis/signin.gui.php",
    "/signup"=>"./guis/signup.gui.php",
    "/cart"=>"./guis/cart.gui.php",
    "/singleProduct"=>"./guis/single_product.gui.php",
    "/orderDetails"=>"./guis/order_details.gui.php",
    "/purchasedHistory"=>"./guis/purchased_history.gui.php",
    "/userProfile"=>"./guis/user_profile.gui.php",
    "/wishlist"=>"./guis/wishlist.gui.php",
    "/myProducts"=>"./guis/my_products.gui.php",
    "/addProduct"=>"./guis/add_product.gui.php",
    "/manageUsers"=>"./guis/admin/manage_users.gui.php",
    "/manageProduct"=>"./guis/admin/manage_product.gui.php",
    "/sellingHistory"=>"./guis/admin/selling_history.gui.php",
    "/writeReviews"=>"./guis/write_reviews.gui.php",
    "/editProduct"=>"./guis/edit_product.gui.php",
    "/adminDashboard"=>"./guis/admin/admin_dashboard.gui.php",
    "/contactAdmin"=>"./guis/contact_admin.gui.php",
    "/manageCategory"=>"./guis/admin/manage_category.gui.php",
    "/manageReviews"=>"./guis/admin/manage_reviews.gui.php",
    "/adminSignin"=>"./guis/admin/admin_signin.gui.php",
    "/manageSellers"=>"./guis/admin/manage_sellers.gui.php",
    "/adminSettings"=>"./guis/admin/admin_settings.gui.php",
    "/search"=>"./guis/search.gui.php",
    "/orderStatus"=>"./guis/order_status.gui.php",

    ]; ?>
